#!/usr/bin/perl -w

#
# my_ip.pl
#
# Developed by Dinesh D <dinesh@exceleron.com>
# Copyright (c) 2014 Exceleron Inc
# Licensed under terms of GNU General Public License.
# All rights reserved.
#
# Changelog:
# 2014-07-07 - created
#

use strict;


print "Content-type: text/html\n\n";

print $ENV{REMOTE_ADDR};

exit;
